/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import domain.Pais;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose
 */
public class VistaAgregar extends javax.swing.JFrame implements InterfaceVistaAgregar {

    private boolean cambiosRealizados = false;

    /**
     * Creates new form VistaAgregar
     */
    public VistaAgregar() {
        initComponents();
    }

    public void limpiarCampos() {
        edadText.setText("");
        pesoText.setText("");
        comboEspecie.setSelectedIndex(0);
        comboPais.setSelectedIndex(0);
        comboSectores.setSelectedIndex(0);
        etiquetaTipoAlimentacion.setText("");

        cambiosRealizados = false; // Reiniciás la bandera
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboEspecie = new javax.swing.JComboBox<>();
        edadText = new javax.swing.JTextField();
        comboSectores = new javax.swing.JComboBox<>();
        pesoText = new javax.swing.JTextField();
        etiquetaTipoAlimentacion = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        botonAgregar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        comboPais = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Peso");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 10));

        jLabel3.setText("Especie");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel4.setText("Sector");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel7.setText("Pais:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel1.setText("Edad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel5.setText("Tipo de alimentacion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        comboEspecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione especie", "León", "Tigre", "Jirafa", "Elefante" }));
        comboEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEspecieActionPerformed(evt);
            }
        });
        jPanel1.add(comboEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        edadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadTextActionPerformed(evt);
            }
        });
        jPanel1.add(edadText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 70, -1));

        comboSectores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la especie" }));
        comboSectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSectoresActionPerformed(evt);
            }
        });
        jPanel1.add(comboSectores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        pesoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoTextActionPerformed(evt);
            }
        });
        jPanel1.add(pesoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 70, -1));
        jPanel1.add(etiquetaTipoAlimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 60, 20));

        botonSalir.setText("Salir");
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        botonAgregar.setText("Agregar");
        jPanel1.add(botonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        jLabel6.setText("años");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel8.setText("kg");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        comboPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione pais" }));
        jPanel1.add(comboPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEspecieActionPerformed
        String especieSeleccionada = comboEspecie.getSelectedItem().toString();
        actualizarComboSectores(especieSeleccionada);
    }//GEN-LAST:event_comboEspecieActionPerformed

    private void edadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadTextActionPerformed

    private void comboSectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSectoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSectoresActionPerformed

    private void pesoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> comboEspecie;
    private javax.swing.JComboBox<String> comboPais;
    private javax.swing.JComboBox<String> comboSectores;
    private javax.swing.JTextField edadText;
    private javax.swing.JLabel etiquetaTipoAlimentacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pesoText;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ejecutar() {
        this.setVisible(true);
    }

    @Override
    public void setControlador(Controlador c) {
        botonSalir.setActionCommand(botonSalirInt);
        botonSalir.addActionListener(c);
        botonAgregar.setActionCommand(botonAgregarInt);
        botonAgregar.addActionListener(c);
    }

    @Override
    public int getEdad() {
        try {
            return Integer.parseInt(edadText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese una edad válida.", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
            return -1;
        }

    }

    public double getPeso() {
        try {
            return Double.parseDouble(pesoText.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un peso válido.", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
            return -1;
        }
    }

    @Override
    public String getComboPais() {
        try {
            return comboPais.getSelectedItem().toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un pais válido.", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    public String getComboEspecie() {
        try {
            return comboEspecie.getSelectedItem().toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese una especie válida.", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    @Override
    public int getComboSector() {
        try {
            return Integer.parseInt(comboSectores.getSelectedItem().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un sector válido.", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
            return -1;
        }
    }

    public void setEtiquetaAlimentacion(String alimento) {
        etiquetaTipoAlimentacion.setText(alimento);
    }

    public String getEtiquetaTipoAlimentacion() {
        return etiquetaTipoAlimentacion.getText();
    }

    public void actualizarComboSectores(String especie) {
        comboSectores.removeAllItems();

        if (especie.equals("León") || especie.equals("Tigre")) {
            comboSectores.addItem("2");
            comboSectores.addItem("4");
            setEtiquetaAlimentacion("Carnívoro");
        } else if (especie.equals("Jirafa") || especie.equals("Elefante")) {
            comboSectores.addItem("1");
            comboSectores.addItem("3");
            setEtiquetaAlimentacion("Herbívoro");
        } else {
            comboSectores.addItem("Seleccione la especie");
            setEtiquetaAlimentacion("-");
        }
    }

    public void cargarComboPais(data.Persistencia persistencia) {
        comboPais.removeAllItems();

        for (Pais pais : persistencia.getPaises()) {
            comboPais.addItem(pais.getNombre());
        }
    }

    public boolean isCambiosRealizados() {
        return cambiosRealizados;
    }

    public void setCambiosRealizados(boolean cambiosRealizados) {
        this.cambiosRealizados = cambiosRealizados;
    }

    @Override
    public void cerrar() {
       limpiarCampos(); 
       this.setVisible(false);
    }

    
    
}
